<a href="https://colab.research.google.com/github/chai1anya/CE605aAssingments/blob/main/CE605A_231030015_Assingment0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

#1. Creating a row and column vector using input method and manually.
rowvector,colvector=np.array([3,6,9,56]),np.array([[1],[200],[53],[94]])
print('1.\n',rowvector,'\n',colvector)

#2. Creating a matrix (5 × 5) using the input method as well as manually and save it as “a"
a=np.array([[1,3,7,84,9],[56,73,889,123,43],[54,94,117,369,843],[54,976,512,84,732],[879,224,71,35,84]])
print('2.\n',a)

#3. Getting 3rd row out of the matrix a.
c=a[2]
print('3.\n',c)

#4. Getting 4th column out of the matrix a.
d=a[:,3]
print('4.\n',d)

#5.1 Sortng matrix a row wise
rowsort=a[:,np.argsort(a[1,:])]#Sorts on basis of second row
print('5.1\n',rowsort)
#5.2 Sorting matrix a column wise
colsort=a[np.argsort(a[:,0]),:]#sorts on basis of first column
print('5.2\n',colsort)

#6. Applying for loop in matrix a
b=np.empty((5,5))              #creating an empty matrix called b
for i in range(len(a)):        #this line will give value of row no.
    for j in range(len(a[0])): #this line will give value of column no.
        if a[i,j]>2:           #this line checks wheather any cell value greater than 2
          b[i,j]=a[i,j]*10     #changes cell value of b with 10xcell value of a
        else:
          b[i,j]=a[i,j]        #changes cell value of b with cell value of a
print('6.\n',b)

#7. Adding matrix a and b.
add=a+b
print('7.\n',add)

#8. Subtracting matrix a from b
sub=b-a
print('8.\n',sub)

#9. Multiplying matrix a by b element wise and matrix multiplication.
mul=a*b
matmul=np.matmul(a,b)
print('9.\n',mul,'\n',matmul)

#10. Divide each element of matrix a and b by 18.
diva=a/18
divb=b/18
print('10.\n',diva,'\n',divb)

#11. Finding the inverse, rank, condition number, singular value decomposition and the norm of matrices a and b.
#11.1  Inverse
inverseOFa=np.linalg.inv(a)
inverseOFb=np.linalg.inv(b)
print('11.1\n',inverseOFa,'\n',inverseOFb)
#11.2  Rank
rankOFa=np.linalg.matrix_rank(a)
rankOFb=np.linalg.matrix_rank(b)
print('11.2\n',rankOFa,'\n',rankOFb)
#11.3  Condition Number
condOFa=np.linalg.cond(a)
condOFb=np.linalg.cond(b)
print('11.3\n',condOFa,'\n',condOFb)
#11.4 Singular value decomposition
u,s,vt=np.linalg.svd(b)
print('11.4\n',u,s,vt)
#11.5 Norm of full matrix
normOFa=np.linalg.norm(a)
normOFb=np.linalg.norm(b)
print('11.4\n',normOFa,normOFb)

#12. Finding the norm, inner product and outer product of column vector
#12.1 Norm of column vector
normOFcolvector=np.linalg.norm(colvector)
print('12.1\n',normOFcolvector)
#12.2 Inner and outer product
inner=np.inner(colvector,colvector)
outer=np.outer(colvector,colvector)
print('12.2\n',inner,'\n',outer)

#13. Writing a function called derivative which takes input parameters F(x) and x and gives derivation of function F(x) at x
import math as mt
def derivative(a,x,i=0):
    h=0.01
    if i==1:
        return ((a(x+h)-a(x))/h)
    elif i==2:
        return ((a(x)-a(x-h))/h)
    else:
        return ((a(x+h)-a(x-h))/(2*h))
m,n,o=derivative(mt.exp,0.5,1),derivative(mt.exp,0.5,2),derivative(mt.exp,0.5)
p,q,r=derivative(mt.cos,0.5,1),derivative(mt.cos,0.5,2),derivative(mt.cos,0.5)
print('13\n',m,n,o,'\n',p,q,r)

#14. Reading csv file as dataframe
import pandas as pd
AWS=pd.read_csv('/content/drive/MyDrive/AWS(1).csv')
print('14\n',AWS.head())

1.
 [ 3  6  9 56] 
 [[  1]
 [200]
 [ 53]
 [ 94]]
2.
 [[  1   3   7  84   9]
 [ 56  73 889 123  43]
 [ 54  94 117 369 843]
 [ 54 976 512  84 732]
 [879 224  71  35  84]]
3.
 [ 54  94 117 369 843]
4.
 [ 84 123 369  84  35]
5.1
 [[  9   1   3  84   7]
 [ 43  56  73 123 889]
 [843  54  94 369 117]
 [732  54 976  84 512]
 [ 84 879 224  35  71]]
5.2
 [[  1   3   7  84   9]
 [ 54  94 117 369 843]
 [ 54 976 512  84 732]
 [ 56  73 889 123  43]
 [879 224  71  35  84]]
6.
 [[1.00e+00 3.00e+01 7.00e+01 8.40e+02 9.00e+01]
 [5.60e+02 7.30e+02 8.89e+03 1.23e+03 4.30e+02]
 [5.40e+02 9.40e+02 1.17e+03 3.69e+03 8.43e+03]
 [5.40e+02 9.76e+03 5.12e+03 8.40e+02 7.32e+03]
 [8.79e+03 2.24e+03 7.10e+02 3.50e+02 8.40e+02]]
7.
 [[2.0000e+00 3.3000e+01 7.7000e+01 9.2400e+02 9.9000e+01]
 [6.1600e+02 8.0300e+02 9.7790e+03 1.3530e+03 4.7300e+02]
 [5.9400e+02 1.0340e+03 1.2870e+03 4.0590e+03 9.2730e+03]
 [5.9400e+02 1.0736e+04 5.6320e+03 9.2400e+02 8.0520e+03]
 [9.6690e+03 2.4640e+03 7.8100e+02 3.8500e+02 9.2400e+02